services:
  postgres:
    image: postgres:16
    container_name: turio_postgres
    environment:
      POSTGRES_USER: turio
      POSTGRES_PASSWORD: turio
      POSTGRES_DB: turio
    ports:
      - "5432:5432"
    volumes:
      - turio_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: turio_redis
    ports:
      - "6379:6379"

volumes:
  turio_pgdata:
